services:
  db:
    image: postgres:13.22-alpine3.22
    container_name: db
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    restart: always
  backend:
    build:
      context: .
      dockerfile: Dockerfile