services:
  db:
    image: postgres:18
    # container_name: db
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8089:8089
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_HOST=db
  
  frontend:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
    - ./client:/usr/share/nginx/html/:ro
