apiVersion: v1
kind: Service
metadata:
  name: go-url-shortener-frontend
  labels:
    app.kubernetes.io/name: go-url-shortener
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: go-url-shortener
    app.kubernetes.io/component: frontend
  type: NodePort
  ports: 
  - port: 80
    targetPort: 80
    nodePort: 31000
